ecomapp/urls.py
from django.urls import path
from .views import *


app_name = "ecomapp"
urlpatterns = [

    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact-us/", ContactView.as_view(), name="contact"),
    path("all-products/", AllProductsView.as_view(), name="allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),

    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),

    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),

    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),

    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

    path("search/", SearchView.as_view(), name="search"),

    path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
    path("password-reset/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
    # Admin Side pages

    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),

    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("admin-order-<int:pk>-change/",
         AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(),
         name="adminproductcreate"),


]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Khalti", "Khalti"),
    ("Esewa", "Esewa"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

templates/adminpages/adminbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <a href="{% url 'ecomapp:adminhome' %}">Home</a> | 
        <a href="{% url 'ecomapp:adminorderlist' %}">All Orders</a> | 
        <a href="{% url 'ecomapp:adminproductlist' %}">All Products</a> | 
        <a href="{% url 'ecomapp:home' %}" target="_blank">Visit site</a>
    </div>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/adminpages/adminhome.html
{% extends "adminpages/adminbase.html" %}

{% block title %}Admin Home{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Pending Orders</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID </th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in pendingorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecomapp:adminorderdetail' order.id %}">#ORDER_{{order.id}}</a></td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}}</td>
                        <td>{{order.total}}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/adminpages/adminlogin.html
{% extends 'base.html' %}

{% block title %}Admin Login{% endblock %}

{% block content %}
<style>
    .errorlist {
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Admin Login Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Login as a Admin</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/adminpages/adminorderdetail.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}

{% block title %}Order Detail{% endblock  %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Detail</h3>
            <hr>
            <p><span class="font-weight-bold">Order ID: </span> #ORDER_{{ord_obj.id}}</p>
            <p><span class="font-weight-bold">Order Status: </span> {{ord_obj.order_status}}</p>
            <p><span class="font-weight-bold">Order On: </span> {{ord_obj.created_at}}({{ord_obj.created_at|timesince}} ago)</p>
            <p><span class="font-weight-bold">Customer Information: </span> By {{ord_obj.ordered_by}}, {{ord_obj.mobile}}</p>
            <p><span class="font-weight-bold">Shipping Address: </span> By {{ord_obj.shipping_address}} ({{ord_obj.email}})</p>
            <p><span class="font-weight-bold">Payment Information: </span>  Using {{ord_obj.payment_method}} ({% if ord_obj.payment_completed %}Payment Completed{% else %}Not Paid{% endif %})</p>
            <h4>Ordered Items</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a target="_blank"
                                href="{% url 'ecomapp:productdetail' cp.product.slug %}">{{cp.product.title}}({{cp.product.id}})</a>
                        </td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total: </th>
                        <th>Rs {{ord_obj.total|intcomma}}/-</th>
                    </tr>
                </tbody>
            </table>
            <form action="{% url 'ecomapp:adminorderstatuschange' ord_obj.id %}" method="POST">
                {% csrf_token %}
                <select name="status">
                    {% for i, j in allstatus %}
                    <option value="{{i}}" {% if i == ord_obj.order_status %}selected{% endif %}>{{j}}</option>
                    {% endfor %}
                </select>
                <button class="btn btn-info">Change</button>
                
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/adminpages/adminorderlist.html
{% extends 'adminpages/adminbase.html' %}

{% block title %}All Orders {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>All Orders</h3><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID </th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in allorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecomapp:adminorderdetail' order.id %}">#ORDER_{{order.id}}</a></td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}}</td>
                        <td>{{order.total}}</td>
                        <td>{{order.order_status}}</td>
            
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/adminpages/adminproductcreate.html
{% extends 'adminpages/adminbase.html' %}

{% block title %}Add New Product{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10 mx-auto">
            <h3>Add New product</h3>
            <hr>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-info">Submit Data</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/adminpages/adminproductlist.html
{% extends 'adminpages/adminbase.html' %}
{% block title %}All Products{% endblock %}


{% block content %}
<div class="container"> 
    <div class="row">
        <div class="col-md-12">
            <h3>All Product list</h3><hr>
            <a href="{% url 'ecomapp:adminproductcreate' %}">Add New Product</a>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product Title</th>
                        <th>Image</th>
                        <th>Price</th>
                        <th>Views</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in allproducts %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{p.title}}</td>
                        <td><img src="{{p.image.url}}" style="height: 60px;" alt=""></td>
                        <td>{{p.selling_price}}</td>
                        <td>{{p.view_count}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}